=== korn1k/xml_xsl_timetable/timetable.xsd
<?xml version="1.0"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="student">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" minOccurs="1" maxOccurs="1" type="xs:string" />
                <xs:element name="id-number" minOccurs="1" maxOccurs="1" type="xs:unsignedInt" />
                <xs:element name="program-of-study" minOccurs="0" maxOccurs="1" type="xs:string" />
                <xs:element name="name-of-school" minOccurs="0" maxOccurs="1" type="xs:string" />
                <xs:element name="school-term" minOccurs="1" maxOccurs="1" type="xs:string" />
                <xs:element name="timetable" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element minOccurs="5" maxOccurs="5" name="day">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element minOccurs="0" maxOccurs="1" name="classes">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element minOccurs="0" maxOccurs="13" name="class">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element minOccurs="1" maxOccurs="1" name="time">
                                                                    <xs:complexType>
                                                                        <xs:attribute name="start" use="required">
                                                                            <xs:simpleType>
                                                                                <xs:restriction base="xs:unsignedShort">
                                                                                    <xs:minInclusive value="800" />
                                                                                    <xs:maxInclusive value="2000" />
                                                                                </xs:restriction>
                                                                            </xs:simpleType>
                                                                        </xs:attribute>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                            <xs:attribute name="course-code" use="required">
                                                                <xs:simpleType>
                                                                    <xs:restriction base="xs:string">
                                                                        <xs:pattern value="[A-Z][A-Z][A-Z][A-Z][-][0-9][0-9][0-9][0-9]" />
                                                                    </xs:restriction>
                                                                </xs:simpleType>
                                                            </xs:attribute>
                                                            <xs:attribute name="room-number" type="xs:string" use="required" />
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="name" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="Monday" />
                                                <xs:enumeration value="Tuesday" />
                                                <xs:enumeration value="Wednesday" />
                                                <xs:enumeration value="Thursday" />
                                                <xs:enumeration value="Friday" />
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                    <xs:unique name="unique-day">
                        <xs:selector xpath="day" />
                        <xs:field xpath="@name" />
                    </xs:unique>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== korn1k/xml_xsl_timetable/student-3.xml
<?xml version='1.0' encoding='UTF-8'?>
<student xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' 
    xsi:noNamespaceSchemaLocation='timetable.xsd'>
    <name>Mykyta Koryliuk</name>
    <!-- An invalid student ID number: 0.93 -->
    <id-number>0.93</id-number>
    <!-- A missing REQUIRED element: program-of-study -->
    <name-of-school>Fanshawe College, West-London Campus</name-of-school>
    <school-term>W2020</school-term>
    <!-- An element that is no defined in the schema: extra-classes -->
    <extra-class>Math</extra-class>
    <timetable>
        <day name="Monday">
            <classes>
                <class course-code='INFO-1080-02' room-number='H2001'>
                    <!-- An invalid start time for an Hour field that isn't a multiple of 100: 80-->
                    <time start='80' end='90' />
                </class>
            </classes>
        </day>
        <!-- Duplicate day fields: 2 Monday -->
        <day name="Monday"></day>
        <day name="Tuesdaasasy">
            <classes>
                <!-- An invalid course code: 444 -->
                <class course-code='444' room-number='H1111'>
                    <time start='1100' end='1300' />
                </class>
                <class course-code='INFO-2221-01' room-number='H4434'>
                    <time start='1300' end='1400' />
                </class>
            </classes>
        </day>
        <!-- A missing REQUIRED attribute: name -->
        <day>
            <classes>
                <class course-code='INFO-8976-01' room-number='H1023'>
                    <time start='1000' end='1200' />
                </class>
            </classes>
        </day>
        <!-- An invalid number of Day fields: Friday -->
    </timetable>
</student>

=== korn1k/xml_xsl_timetable/student-1.xml
<?xml version='1.0' encoding='UTF-8'?>
<student xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' 
    xsi:noNamespaceSchemaLocation='timetable.xsd'>
    <name>Mykyta Koryliuk</name>
    <id-number>0939330</id-number>
    <program-of-study>Internet Applications and Web-Development (IWD)</program-of-study>
    <name-of-school>Fanshawe College, West-London Campus</name-of-school>
    <school-term>W2020</school-term>
    <timetable>
        <day name="Monday">
            <classes>
                <class course-code='INFO-1080' room-number='H2001'>
                    <time start='800' />
                </class>
                <class course-code='INFO-7080' room-number='H1001'>
                    <time start='1200' />
                </class>
                <class course-code='INFO-7810' room-number='H0001'>
                    <time start='1400' />
                </class>
            </classes>
        </day>
        <day name="Tuesday" />
        <day name="Wednesday">
            <classes>
                <class course-code='INFO-5654' room-number='H2541'>
                    <time start='1100' />
                </class>
                <class course-code='INFO-8888' room-number='H1781'>
                    <time start='1400' />
                </class>
            </classes>
        </day>
        <day name="Thursday">
            <classes>
                <class course-code='INFO-7555' room-number='H9431'>
                    <time start='900' />
                </class>
            </classes>
        </day>
        <day name="Friday" />
    </timetable>
</student>
